{% set version = "0.1.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modelr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modelr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modelr/modelr_{{ version }}.tar.gz
  sha256: c6fbd4257edc70875dd4e5f70499663623be9cd984aa0a4f480c3425d51896da

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-broom
    - r-dplyr
    - r-magrittr
    - r-purrr >=0.2.2
    - r-rlang >=0.2.0
    - r-tibble
    - r-tidyr >=0.8.0
  run:
    - r-base
    - r-broom
    - r-dplyr
    - r-magrittr
    - r-purrr >=0.2.2
    - r-rlang >=0.2.0
    - r-tibble
    - r-tidyr >=0.8.0

test:
  commands:
    - $R -e "library('modelr')"           # [not win]
    - "\"%R%\" -e \"library('modelr')\""  # [win]

about:
  home: https://modelr.tidyverse.org, https://github.com/tidyverse/modelr
  license: GPL-3
  summary: Functions for modelling that help you seamlessly integrate modelling into a pipeline of data manipulation and visualisation.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: modelr
# Title: Modelling Functions that Work with the Pipe
# Version: 0.1.4
# Authors@R:  c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com"), person(given = "RStudio", role = "cph"))
# Description: Functions for modelling that help you seamlessly integrate modelling into a pipeline of data manipulation and visualisation.
# License: GPL-3
# URL: https://modelr.tidyverse.org, https://github.com/tidyverse/modelr
# BugReports: https://github.com/tidyverse/modelr/issues
# Depends: R (>= 3.1)
# Imports: broom, dplyr, magrittr, purrr (>= 0.2.2), rlang (>= 0.2.0), tibble, tidyr (>= 0.8.0)
# Suggests: compiler, covr, ggplot2, testthat
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-02-18 13:48:09 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-02-18 22:00:03 UTC
