appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ovj+3TyE6G8Ihh7RjGvDbVV1MEfkatptwud7cPUIEG6p1dmx7iGBC75NVSmt0B7L2+CGfoKEBl+VI4pCDXjKrLcNeaM0Gla3OSZaRIGow5+/K5ZdhMMLO9JhvA/MTz1MRWpwoDnyTX9An7/4VW6usSrjYDl3hIZo4ap23UUwdob6QbiIgz3tbMcOr3N5JUR5JdOT4CWieKBwfD1jsVU29u3ff7Dj5jWijn/buJojQofVbcSMOzyt1dCgFJOEG6l1U0g39sJI5yrEHudPEYZjLC9bbMx6LZCy5ljkuLINgwBZd4q6iLvqV+REn6FnKRIrBk59mzHgEO/lhT1QPkT5sWioMWTJwZCtffqaA3XLvNV9BxDpdSxPaU15yH5cCkPAKS4/yXSERYbn0iQrpva96/YKh62OsAfkPLRzaz6J0awUFHyXZZpglSI8jvWotMgHUNESJqrOauYsRKxf3/2WPUxDgni6Wyq7A2SaCEj8mko1ErKuSFuBgS9UlJF+XvFtoe9p8J7il2nVR5T/SKSFiT5YN7q+S6sv1GaqTrf/YZ9/h5pDhVES5EXlI3NeqdDA4dpXDnzkiZysrOw5XBgkjnCLnWyOgXyPZr5X5eUhxydPoRZSoDFQoC3qVXAzv53U/QBAd8/3Mw/JJUwYgvMhzyJl4Tr0M7T62/X4KeHIoWE=
conda_forge_output_validation: true
